#!/usr/bin/env bash
# install.sh — dotfiles installer
# Tested on Debian/Ubuntu x86_64, aarch64, armv7.
#
# Everything installs under $HOME. No sudo: apt-get download + dpkg -x, pip
# --user, and GitHub release tarballs only.
set -euo pipefail

# Directory containing this script (the dotfiles checkout).
dotfiles_root() {
    cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
}


# ─── Helpers ──────────────────────────────────────────────────────────────────

die()  { echo "  ERROR: $*" >&2; exit 1; }
info() { echo "  $*"; }
header() { echo; echo "── $* ──"; }

# Interactive yes/no (default yes). Returns 0 = yes, 1 = no.
ask() {
    local answer
    while true; do
        read -r -p "  $* [Y/n]: " answer
        answer="${answer:-y}"
        case "$answer" in
            [Yy]*) return 0 ;;
            [Nn]*) return 1 ;;
        esac
    done
}

have() { command -v "$1" &>/dev/null; }

# Append a literal line to a file only if it is not already present.
append_once() {
    local line="$1" file="$2"
    grep -qxF "$line" "$file" 2>/dev/null || printf '\n%s\n' "$line" >> "$file"
}

# Portable download: prefers curl, falls back to wget.
fetch() {
    local url="$1" dest="$2"
    if have curl; then
        curl -fsSL "$url" -o "$dest"
    elif have wget; then
        wget -q "$url" -O "$dest"
    else
        die "Neither curl nor wget found. Install one and retry."
    fi
}

# Same as fetch but returns 1 on failure (no die).
fetch_soft() {
    local url="$1" dest="$2"
    if have curl; then
        curl -fsSL "$url" -o "$dest" && return 0
    elif have wget; then
        wget -q "$url" -O "$dest" && return 0
    fi
    return 1
}


# ─── Install step convention ─────────────────────────────────────────────────
# Every install_* routine follows the same flow:
#   1. header "Component name"
#   2. If already satisfied → info "… already …" ; return 0
#   3. If automatic install is impossible here → info why ; return 0 (no prompt)
#   4. ask "Install …?" [Y/n] → decline → info "Skipping …." ; return 0
#   5. Download / extract / configure
# Exceptions: check_prerequisites, install_dotfiles (clone is mandatory when repo missing).

vifm_previews_already_configured() {
    [[ -x "${HOME}/.local/bin/vifm-preview" ]] \
        && [[ -f "${HOME}/.config/vifm/vifmimgrc" ]] \
        && grep -Fq 'source ~/.config/vifm/vifmimgrc' "${HOME}/.config/vifm/vifmrc" 2>/dev/null
}


# ─── Pinned versions & arch (sharkdp musl tarballs, vifm) ─────────────────────

FD_VERSION="10.4.2"
BAT_VERSION="0.26.1"
VIFM_VERSION="0.14.3"
# Static Linux binary from https://hpjansson.org/chafa/releases/static/ (apt download often fails over SSH).
CHAFA_VERSION="1.18.2"

# Target triple for sharkdp fd/bat musl .tar.gz releases.
github_musl_triple() {
    case "$(uname -m)" in
        x86_64)        echo "x86_64-unknown-linux-musl" ;;
        aarch64|arm64) echo "aarch64-unknown-linux-musl" ;;
        armv7*)        echo "arm-unknown-linux-musleabihf" ;;
        *)             echo "x86_64-unknown-linux-musl" ;;
    esac
}


# ─── Unified shell env (PATH, LD_LIBRARY_PATH for user-local installs) ────────
# Everything lands under ~/.local; this file is sourced by dotfiles .bashrc.

refresh_dotfiles_env() {
    mkdir -p "$HOME/.local/share/dotfiles"
    local envf triple libpath
    envf="$HOME/.local/share/dotfiles/env.sh"
    case "$(uname -m)" in
        x86_64)        triple=x86_64-linux-gnu ;;
        aarch64|arm64) triple=aarch64-linux-gnu ;;
        armv7l)        triple=arm-linux-gnueabihf ;;
        *)             triple=x86_64-linux-gnu ;;
    esac
    libpath="$HOME/.local/opt/vifm-deps/usr/lib/$triple"

    {
        echo '# Generated by ~/dotfiles/install.sh — do not edit by hand'
        echo 'export PATH="$HOME/.local/bin${PATH:+:$PATH}"'
        echo '[[ -d "$HOME/.fzf/bin" ]] && PATH="$HOME/.fzf/bin:$PATH"'
        echo '# Append vifm-deps so ~/.local/bin wins (e.g. static chafa over apt-extracted binary).'
        echo '[[ -d "$HOME/.local/opt/vifm-deps/usr/bin" ]] && PATH="$PATH:$HOME/.local/opt/vifm-deps/usr/bin"'
        echo 'export PATH'
        echo "if [[ -d \"$libpath\" ]]; then"
        echo "  export LD_LIBRARY_PATH=\"$libpath\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}\""
        echo 'fi'
    } > "$envf"
}


# ─── Prerequisites ────────────────────────────────────────────────────────────

check_prerequisites() {
    header "Prerequisites"
    have git || die "git is required but not found. Install git and retry."
    info "git: ok"
}


# ─── Dotfiles ─────────────────────────────────────────────────────────────────

install_dotfiles() {
    header "Dotfiles"

    if [[ -d ~/dotfiles ]]; then
        info "~/dotfiles repo already present."
    else
        ask "Clone https://github.com/22or/dotfiles.git into ~/dotfiles?" \
            || die "This installer expects ~/dotfiles."
        git clone https://github.com/22or/dotfiles.git ~/dotfiles
        info "Cloned into ~/dotfiles."
    fi

    # .vimrc symlink
    if [[ -L ~/.vimrc ]] && [[ "$(readlink -f ~/.vimrc 2>/dev/null)" == "$(readlink -f ~/dotfiles/.vimrc 2>/dev/null)" ]]; then
        info "~/.vimrc → ~/dotfiles/.vimrc already configured."
    elif [[ -L ~/.vimrc ]]; then
        info "~/.vimrc is a symlink (not pointing at ~/dotfiles/.vimrc). Leaving unchanged."
    elif [[ -e ~/.vimrc ]]; then
        info "WARNING: ~/.vimrc exists and is not a symlink. Skipping to avoid data loss."
        info "         Back it up and rerun, or manually: ln -sf ~/dotfiles/.vimrc ~/.vimrc"
    else
        ln -s ~/dotfiles/.vimrc ~/.vimrc
        info "Linked ~/.vimrc → ~/dotfiles/.vimrc"
    fi

    # Source dotfiles/.bashrc from ~/.bashrc
    local source_line='source "$HOME/dotfiles/.bashrc"'
    append_once "$source_line" ~/.bashrc
    info "~/.bashrc: ensured source line for ~/dotfiles/.bashrc."
}


# ─── vim-plug ─────────────────────────────────────────────────────────────────
# The vimrc uses vim-plug (call plug#begin / call plug#end).
# Without plug.vim, Vim will throw errors on every startup.

install_vim_plug() {
    header "vim-plug"

    local plug_path=~/.vim/autoload/plug.vim

    if [[ -f "$plug_path" ]]; then
        info "vim-plug already installed (~/.vim/autoload/plug.vim)."
        return
    fi

    ask "vim-plug missing. Download plug.vim and run :PlugInstall?" \
        || { info "Skipping vim-plug."; return 0; }

    info "Installing vim-plug..."
    mkdir -p ~/.vim/autoload
    fetch \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
        "$plug_path"

    info "Running :PlugInstall (this may take a moment)..."
    # -E: skip .vimrc, pick it up via -u; -s: silent batch mode
    vim -es -u ~/.vimrc +PlugInstall +qall || true
    info "Plugins installed."
}


# ─── fzf ──────────────────────────────────────────────────────────────────────
# The vimrc binds <C-p> to :Files (fzf.vim).
# The bashrc sources fzf key-bindings and defines FZF_* env vars.
# The bashrc's key-bindings path (/usr/share/doc/fzf/examples/...) only exists
# for apt-installed fzf. A fallback for git-installed fzf is appended below.

install_fzf() {
    header "fzf"

    if have fzf; then
        info "fzf already installed ($(command -v fzf))."
        _ensure_fzf_keybindings
        return
    fi

    ask "fzf not found. Clone junegunn/fzf into ~/.fzf and run its installer?" \
        || { info "Skipping fzf."; return 0; }

    if [[ -d ~/.fzf ]]; then
        info "~/.fzf exists — running upstream install."
    else
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    fi

    # --no-update-rc  : PATH comes from ~/.local/share/dotfiles/env.sh
    ~/.fzf/install --no-update-rc --key-bindings --completion

    _ensure_fzf_keybindings
    info "fzf → ~/.fzf"
}

# The dotfiles .bashrc sources the apt path for fzf key-bindings. If fzf was
# installed from git, that file doesn't exist and bindings are silently absent.
# Append a fallback that covers the git-installed location.
_ensure_fzf_keybindings() {
    local git_bindings='[[ -f ~/.fzf/shell/key-bindings.bash ]] && source ~/.fzf/shell/key-bindings.bash'
    append_once "$git_bindings" ~/.bashrc
    info "fzf key-bindings fallback ensured in ~/.bashrc"
}


# ─── fd ───────────────────────────────────────────────────────────────────────
# vimrc / bashrc expect the command name 'fdfind'. Binary under ~/.local/opt/fd.

install_fd() {
    header "fd (fdfind)"

    if have fdfind; then
        info "fdfind already available ($(command -v fdfind))."
        return
    fi

    if have fd; then
        mkdir -p ~/.local/bin
        ln -sf "$(command -v fd)" ~/.local/bin/fdfind
        info "Linked fdfind → $(command -v fd) (system fd)."
        return
    fi

    ask "Download fd v${FD_VERSION} (musl) into ~/.local/opt/fd and link fdfind?" \
        || { info "Skipping fd."; return 0; }

    local triple archive url tmpdir optdir
    triple=$(github_musl_triple)
    archive="fd-v${FD_VERSION}-${triple}.tar.gz"
    url="https://github.com/sharkdp/fd/releases/download/v${FD_VERSION}/${archive}"
    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    info "Downloading ${archive}..."
    fetch "$url" "$tmpdir/$archive"

    optdir="$HOME/.local/opt/fd"
    mkdir -p "$optdir"
    tar -xzf "$tmpdir/$archive" -C "$optdir" --strip-components=1

    mkdir -p ~/.local/bin
    ln -sf "$optdir/fd" ~/.local/bin/fd
    ln -sf "$optdir/fd" ~/.local/bin/fdfind
    info "fd installed → ~/.local/opt/fd, ~/.local/bin/{fd,fdfind}"

    trap - RETURN INT TERM
}


# ─── vifm ─────────────────────────────────────────────────────────────────────
# Binary into ~/.local/bin. vifm previews (vifm-preview script) — separate step.

install_vifm() {
    header "vifm"

    if have vifm; then
        info "vifm already installed ($(command -v vifm))."
        return
    fi

    case "$(uname -m)" in
        x86_64) ;;
        *)
            if ! have apt-get; then
                info "vifm: no bundled installer for $(uname -m) without apt-get — install vifm yourself, then rerun."
                return 0
            fi
            ;;
    esac

    ask "Install vifm v${VIFM_VERSION} into ~/.local/bin?" \
        || { info "Skipping vifm."; return 0; }

    local tmpdir
    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    mkdir -p "$HOME/.local/bin"

    case "$(uname -m)" in
        x86_64)
            info "Downloading vifm ${VIFM_VERSION} AppImage (no root needed)..."
            local appimg="$tmpdir/vifm.AppImage"
            fetch \
                "https://github.com/vifm/vifm/releases/download/v${VIFM_VERSION}/vifm-v${VIFM_VERSION}-x86_64.AppImage" \
                "$appimg"
            chmod +x "$appimg"
            ( cd "$tmpdir" && ./vifm.AppImage --appimage-extract >/dev/null )
            cp "$tmpdir/squashfs-root/usr/bin/vifm" "$HOME/.local/bin/vifm"
            ;;
        *)
            # apt-get download + dpkg -x extract the .deb without installing system-wide (no sudo).
            if ! have apt-get; then
                die "apt-get disappeared — cannot download vifm .deb."
            fi
            info "Downloading vifm .deb with apt-get download (no sudo)..."
            ( cd "$tmpdir" && apt-get download vifm ) || die "apt-get download failed. Install vifm manually."
            dpkg -x "$tmpdir"/vifm_*.deb "$tmpdir/pkg"
            cp "$tmpdir/pkg/usr/bin/vifm" "$HOME/.local/bin/vifm"
            ;;
    esac

    info "vifm → ~/.local/bin/vifm"

    trap - RETURN INT TERM
}


# ─── vifm preview stack (chafa images + text/binary via vifm-preview) ─────

# Download .debs with apt-get (no install privileges) and merge into ~/.local/opt/vifm-deps.
# On many SSH boxes apt indices exist but apt-get download fails; install_chafa_static fills the gap.
install_vifm_apt_debs() {
    have apt-get || return 0
    have apt-cache || return 0

    local outdir="$HOME/.local/opt/vifm-deps"
    mkdir -p "$outdir"
    local tmpdir
    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    local pkgs=(
        chafa
        libwebpdemux2
        libwebp7
        poppler-utils
        mediainfo
    )
    local p deb
    for p in "${pkgs[@]}"; do
        apt-cache show "$p" &>/dev/null || continue
        (cd "$tmpdir" && apt-get download "$p" 2>/dev/null) || continue
        shopt -s nullglob
        for deb in "$tmpdir"/*.deb; do
            dpkg -x "$deb" "$outdir" || true
            rm -f "$deb"
        done
        shopt -u nullglob
    done

    trap - RETURN INT TERM
}

# Official glibc-linked static tarball (no libwebp). Do not use `have chafa`: a broken apt chafa
# earlier on PATH must not skip installing ~/.local/bin/chafa.
install_chafa_static() {
    [[ -x "$HOME/.local/bin/chafa" ]] && return 0

    local triple archive url tmpdir binroot binpath
    case "$(uname -m)" in
        x86_64)        triple=x86_64-linux-gnu ;;
        armv7l|armv6*) triple=armv7l-linux-gnu ;;
        aarch64|arm64)
            info "chafa: no hpjansson.org static tarball for aarch64; install the distro package or fix apt-get download."
            return 0
            ;;
        *)
            info "chafa: no static build for arch $(uname -m); install chafa from your distro."
            return 0
            ;;
    esac

    archive="chafa-${CHAFA_VERSION}-1-${triple}.tar.gz"
    url="https://hpjansson.org/chafa/releases/static/${archive}"

    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    fetch_soft "$url" "$tmpdir/$archive" || {
        info "chafa: could not fetch ${url}. Install chafa from your package manager."
        trap - RETURN INT TERM
        return 0
    }

    tar -xzf "$tmpdir/$archive" -C "$tmpdir" || {
        trap - RETURN INT TERM
        return 0
    }

    binroot="$tmpdir/chafa-${CHAFA_VERSION}-1-${triple}"
    binpath="$binroot/chafa"
    [[ -x "$binpath" ]] || {
        trap - RETURN INT TERM
        return 0
    }

    mkdir -p "$HOME/.local/bin"
    cp -f "$binpath" "$HOME/.local/bin/chafa"
    chmod +x "$HOME/.local/bin/chafa"
    info "chafa → ~/.local/bin/chafa (static ${CHAFA_VERSION})"

    trap - RETURN INT TERM
}

install_bat_release() {
    have batcat && return 0
    have bat && return 0

    local triple archive url tmpdir extract_dir
    triple=$(github_musl_triple)
    archive="bat-v${BAT_VERSION}-${triple}.tar.gz"
    url="https://github.com/sharkdp/bat/releases/download/v${BAT_VERSION}/${archive}"

    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    fetch_soft "$url" "$tmpdir/$archive" || {
        trap - RETURN INT TERM
        return 0
    }

    tar -xzf "$tmpdir/$archive" -C "$tmpdir" || {
        trap - RETURN INT TERM
        return 0
    }

    extract_dir="$tmpdir/bat-v${BAT_VERSION}-${triple}"
    [[ -x "$extract_dir/bat" ]] || {
        trap - RETURN INT TERM
        return 0
    }

    mkdir -p "$HOME/.local/bin"
    cp -f "$extract_dir/bat" "$HOME/.local/bin/bat"
    chmod +x "$HOME/.local/bin/bat"
    ln -sf "$HOME/.local/bin/bat" "$HOME/.local/bin/batcat" 2>/dev/null || true

    trap - RETURN INT TERM
}

install_vifm_preview_tooling() {
    header "vifm preview tooling (deps)"

    install_vifm_apt_debs
    refresh_dotfiles_env
    install_bat_release
    refresh_dotfiles_env
}


install_vifm_previews() {
    header "vifm previews (chafa + vifm-preview)"

    local root
    root=$(dotfiles_root)
    if [[ ! -r "$root/vifm/vifm-preview" ]]; then
        return 0
    fi

    bash --norc --noprofile -c "source '${root}/.bashrc' && vifm-preview-install"
}


# Optional vifm previews: check first, ask only if not already complete.

install_vifm_previews_optional() {
    header "vifm previews"

    if vifm_previews_already_configured; then
        info "vifm previews already installed (vifm-preview, chafa rules in vifmimgrc)."
        return 0
    fi

    ask "Set up vifm previews (chafa, bat, poppler-utils, mediainfo via apt download)?" \
        || { info "Skipping vifm previews."; return 0; }

    install_vifm_preview_tooling
    install_vifm_previews
}


# ─── Bashmarks ────────────────────────────────────────────────────────────────
# Provides s, g, p, d, l commands for saving and jumping to directories.
# https://github.com/huyng/bashmarks

install_bashmarks() {
    header "Bashmarks"

    if [[ -f ~/.local/bin/bashmarks.sh ]]; then
        info "Bashmarks already installed (~/.local/bin/bashmarks.sh)."
        return
    fi

    ask "Install Bashmarks (s/g/p/d/l directory bookmarks)?" \
        || { info "Skipping Bashmarks."; return 0; }

    local tmpdir=""
    trap '[[ -n "$tmpdir" ]] && rm -rf "$tmpdir"' RETURN INT TERM
    tmpdir=$(mktemp -d)

    git clone https://github.com/huyng/bashmarks.git "$tmpdir"
    make -C "$tmpdir" install
    info "Bashmarks installed to ~/.local/bin/bashmarks.sh"

    trap - RETURN INT TERM
}


# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
    echo
    echo "════════════════════════════════════"
    echo "  Dotfiles Installer"
    echo "════════════════════════════════════"

    check_prerequisites
    install_dotfiles
    install_vim_plug
    install_fzf
    install_fd
    install_bashmarks
    install_vifm
    install_vifm_previews_optional

    install_chafa_static

    refresh_dotfiles_env

    echo
    echo "════════════════════════════════════"
    echo "  Done.  source ~/.bashrc"
    echo "════════════════════════════════════"
    echo
}

main
