#!/usr/bin/env bash
# install.sh — dotfiles installer
# Tested on Debian/Ubuntu x86_64, aarch64, armv7.
#
# Everything installs under $HOME. No sudo: apt-get download + dpkg -x, pip
# --user, and GitHub release tarballs only.
set -euo pipefail

[[ -n "${DOTFILES_ROOT+set}" ]] && _DOTFILES_ROOT_FROM_ENV=1
# shellcheck source=lib/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

# curl | bash leaves BASH_SOURCE empty; re-exec from the checkout so all steps use DOTFILES_ROOT.
bootstrap_dotfiles_checkout() {
    local src="${BASH_SOURCE[0]:-}"

    if [[ -n "$src" && -f "$src" ]]; then
        local dir
        dir=$(cd "$(dirname "$src")" && pwd)
        if [[ -f "$dir/.bashrc" && -f "$dir/install.sh" ]]; then
            if (( !_DOTFILES_ROOT_FROM_ENV )); then
                DOTFILES_ROOT="$dir"
                export DOTFILES_ROOT
            fi
        fi
        if [[ "$(readlink -f "$src")" == "$(readlink -f "$DOTFILES_ROOT/install.sh")" ]]; then
            return 0
        fi
    fi

    if [[ ! -d "$DOTFILES_ROOT" ]]; then
        header "Dotfiles"
        ask "Clone https://github.com/22or/dotfiles.git into $DOTFILES_ROOT?" \
            || die "This installer expects a dotfiles checkout at $DOTFILES_ROOT."
        git clone https://github.com/22or/dotfiles.git "$DOTFILES_ROOT"
        info "Cloned into $DOTFILES_ROOT."
    fi

    [[ -f "$DOTFILES_ROOT/install.sh" ]] \
        || die "missing $DOTFILES_ROOT/install.sh"

    export DOTFILES_ROOT
    exec bash "$DOTFILES_ROOT/install.sh" "$@"
}


# ─── Install step convention ─────────────────────────────────────────────────
# Every install_* routine follows the same flow:
#   1. header "Component name"
#   2. If already satisfied → info "… already …" ; return 0
#   3. If automatic install is impossible here → info why ; return 0 (no prompt)
#   4. ask "Install …?" [Y/n] → decline → info "Skipping …." ; return 0
#   5. Download / extract / configure
# Exceptions: check_prerequisites, install_dotfiles (clone is mandatory when repo missing).

# ─── Pinned versions & arch (sharkdp musl tarballs, vifm) ─────────────────────

FD_VERSION="10.4.2"
BAT_VERSION="0.26.1"
VIFM_VERSION="0.14.3"
# Static Linux binary from https://hpjansson.org/chafa/releases/static/ (apt download often fails over SSH).
CHAFA_VERSION="1.18.2"

# Target triple for sharkdp fd/bat musl .tar.gz releases.
github_musl_triple() {
    case "$(uname -m)" in
        x86_64)        echo "x86_64-unknown-linux-musl" ;;
        aarch64|arm64) echo "aarch64-unknown-linux-musl" ;;
        armv7*)        echo "arm-unknown-linux-musleabihf" ;;
        *)             echo "x86_64-unknown-linux-musl" ;;
    esac
}


# ─── Unified shell env (PATH, LD_LIBRARY_PATH for user-local installs) ────────
# Everything lands under ~/.local; this file is sourced by dotfiles .bashrc.

refresh_dotfiles_env() {
    mkdir -p "$HOME/.local/share/dotfiles"
    local envf triple libpath
    envf="$HOME/.local/share/dotfiles/env.sh"
    case "$(uname -m)" in
        x86_64)        triple=x86_64-linux-gnu ;;
        aarch64|arm64) triple=aarch64-linux-gnu ;;
        armv7l)        triple=arm-linux-gnueabihf ;;
        *)             triple=x86_64-linux-gnu ;;
    esac
    libpath="$HOME/.local/opt/vifm-deps/usr/lib/$triple"

    {
        echo '# Generated by dotfiles install.sh — do not edit by hand'
        echo 'export PATH="$HOME/.local/bin${PATH:+:$PATH}"'
        echo '[[ -d "$HOME/.fzf/bin" ]] && PATH="$HOME/.fzf/bin:$PATH"'
        echo '# Append vifm-deps so ~/.local/bin wins (e.g. static chafa over apt-extracted binary).'
        echo '[[ -d "$HOME/.local/opt/vifm-deps/usr/bin" ]] && PATH="$PATH:$HOME/.local/opt/vifm-deps/usr/bin"'
        echo 'export PATH'
        echo "if [[ -d \"$libpath\" ]]; then"
        echo "  export LD_LIBRARY_PATH=\"$libpath\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}\""
        echo 'fi'
        echo '# AppImage vifm ncurses needs explicit terminfo (see install_vifm).'
        echo 'if [[ -d "$HOME/.local/opt/vifm/usr/share/terminfo" ]]; then'
        echo '  export TERMINFO="$HOME/.local/opt/vifm/usr/share/terminfo"'
        echo 'elif [[ -d /usr/lib/terminfo ]]; then'
        echo '  export TERMINFO=/usr/lib/terminfo'
        echo 'elif [[ -d /lib/terminfo ]]; then'
        echo '  export TERMINFO=/lib/terminfo'
        echo 'fi'
    } > "$envf"
}


# ─── Prerequisites ────────────────────────────────────────────────────────────

check_prerequisites() {
    header "Prerequisites"
    have git || die "git is required but not found. Install git and retry."
    info "git: ok"
}


# ─── Dotfiles ─────────────────────────────────────────────────────────────────

install_dotfiles() {
    header "Dotfiles"

    info "Using dotfiles at $DOTFILES_ROOT."

    link_dotfile "$DOTFILES_ROOT/.vimrc" ~/.vimrc

    # Source dotfiles/.bashrc from ~/.bashrc
    local bashrc_src="$DOTFILES_ROOT/.bashrc"
    local source_line="source \"$bashrc_src\""
    append_once "$source_line" ~/.bashrc
    info "~/.bashrc: ensured source line for $bashrc_src."

    if vifm_dotfiles_already_configured; then
        info "vifm config already linked (~/.config/vifm, ~/.local/bin/vifm-preview)."
    else
        link_vifm_dotfiles || true
    fi
}


# ─── vim-plug ─────────────────────────────────────────────────────────────────
# The vimrc uses vim-plug (call plug#begin / call plug#end).
# Without plug.vim, Vim will throw errors on every startup.

install_vim_plug() {
    header "vim-plug"

    local plug_path=~/.vim/autoload/plug.vim

    if [[ -f "$plug_path" ]]; then
        info "vim-plug already installed (~/.vim/autoload/plug.vim)."
        return
    fi

    ask "vim-plug missing. Download plug.vim and run :PlugInstall?" \
        || { info "Skipping vim-plug."; return 0; }

    info "Installing vim-plug..."
    mkdir -p ~/.vim/autoload
    fetch \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
        "$plug_path"

    info "Running :PlugInstall (this may take a moment)..."
    vim -es -u "$DOTFILES_ROOT/.vimrc" +PlugInstall +qall || true
    info "Plugins installed."
}


# ─── fzf ──────────────────────────────────────────────────────────────────────
# The vimrc binds <C-p> to :Files (fzf.vim).
# Key-bindings are sourced from dotfiles/.bashrc (apt path or ~/.fzf fallback).

install_fzf() {
    header "fzf"

    if have fzf; then
        info "fzf already installed ($(command -v fzf))."
        return
    fi

    ask "fzf not found. Clone junegunn/fzf into ~/.fzf and run its installer?" \
        || { info "Skipping fzf."; return 0; }

    if [[ -d ~/.fzf ]]; then
        info "~/.fzf exists — running upstream install."
    else
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    fi

    # --no-update-rc  : PATH comes from ~/.local/share/dotfiles/env.sh
    ~/.fzf/install --no-update-rc --key-bindings --completion

    info "fzf → ~/.fzf"
}


# ─── fd ───────────────────────────────────────────────────────────────────────
# vimrc / bashrc expect the command name 'fdfind'. Binary under ~/.local/opt/fd.

install_fd() {
    header "fd (fdfind)"

    if have fdfind; then
        info "fdfind already available ($(command -v fdfind))."
        return
    fi

    if have fd; then
        mkdir -p ~/.local/bin
        ln -sf "$(command -v fd)" ~/.local/bin/fdfind
        info "Linked fdfind → $(command -v fd) (system fd)."
        return
    fi

    ask "Download fd v${FD_VERSION} (musl) into ~/.local/opt/fd and link fdfind?" \
        || { info "Skipping fd."; return 0; }

    local triple archive url tmpdir optdir
    triple=$(github_musl_triple)
    archive="fd-v${FD_VERSION}-${triple}.tar.gz"
    url="https://github.com/sharkdp/fd/releases/download/v${FD_VERSION}/${archive}"
    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    info "Downloading ${archive}..."
    fetch "$url" "$tmpdir/$archive"

    optdir="$HOME/.local/opt/fd"
    mkdir -p "$optdir"
    tar -xzf "$tmpdir/$archive" -C "$optdir" --strip-components=1

    mkdir -p ~/.local/bin
    ln -sf "$optdir/fd" ~/.local/bin/fd
    ln -sf "$optdir/fd" ~/.local/bin/fdfind
    info "fd installed → ~/.local/opt/fd, ~/.local/bin/{fd,fdfind}"

    trap - RETURN INT TERM
}


# ─── vifm ─────────────────────────────────────────────────────────────────────
# Binary into ~/.local/bin. AppImage ncurses needs bundled terminfo (see ensure_vifm_terminfo).

# Download and extract vifm into tmpdir. Prints package tree path on stdout.
vifm_fetch_tree() {
    local tmpdir="$1"
    local tree=""

    case "$(uname -m)" in
        x86_64)
            local appimg="$tmpdir/vifm.AppImage"
            fetch \
                "https://github.com/vifm/vifm/releases/download/v${VIFM_VERSION}/vifm-v${VIFM_VERSION}-x86_64.AppImage" \
                "$appimg"
            chmod +x "$appimg"
            ( cd "$tmpdir" && ./vifm.AppImage --appimage-extract >/dev/null )
            tree="$tmpdir/squashfs-root"
            ;;
        *)
            have apt-get || return 1
            ( cd "$tmpdir" && apt-get download vifm ) || return 1
            dpkg -x "$tmpdir"/vifm_*.deb "$tmpdir/pkg"
            tree="$tmpdir/pkg"
            ;;
    esac

    [[ -n "$tree" && -d "$tree" ]] || return 1
    printf '%s\n' "$tree"
}

copy_vifm_terminfo_from_tree() {
    local tree="$1"
    if [[ ! -d "$tree/usr/share/terminfo" ]]; then
        return 1
    fi
    mkdir -p "$HOME/.local/opt/vifm/usr/share"
    cp -a "$tree/usr/share/terminfo" "$HOME/.local/opt/vifm/usr/share/"
    info "vifm terminfo → ~/.local/opt/vifm/usr/share/terminfo"
}

# AppImage binary in ~/.local/bin cannot resolve TERM without this; also fixes upgrades.
ensure_vifm_terminfo() {
    [[ -f "$HOME/.local/opt/vifm/usr/share/terminfo/x/xterm-256color" ]] && return 0
    [[ -x "$HOME/.local/bin/vifm" ]] || return 0

    local tmpdir tree
    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    info "Fetching vifm ${VIFM_VERSION} package for terminfo..."
    tree=$(vifm_fetch_tree "$tmpdir") || {
        info "vifm terminfo: could not download or extract vifm package."
        trap - RETURN INT TERM
        return 0
    }

    copy_vifm_terminfo_from_tree "$tree" || info "vifm terminfo: none in package tree."
    trap - RETURN INT TERM
}

install_vifm() {
    header "vifm"

    if have vifm; then
        info "vifm already installed ($(command -v vifm))."
        ensure_vifm_terminfo
        return
    fi

    case "$(uname -m)" in
        x86_64) ;;
        *)
            if ! have apt-get; then
                info "vifm: no bundled installer for $(uname -m) without apt-get — install vifm yourself, then rerun."
                return 0
            fi
            ;;
    esac

    ask "Install vifm v${VIFM_VERSION} into ~/.local/bin?" \
        || { info "Skipping vifm."; return 0; }

    local tmpdir
    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    mkdir -p "$HOME/.local/bin"

    local tree
    info "Downloading vifm ${VIFM_VERSION}..."
    tree=$(vifm_fetch_tree "$tmpdir") || die "vifm download or extract failed."
    cp "$tree/usr/bin/vifm" "$HOME/.local/bin/vifm"
    copy_vifm_terminfo_from_tree "$tree" || true

    info "vifm → ~/.local/bin/vifm"

    trap - RETURN INT TERM
}


# ─── vifm preview stack (chafa images + text/binary via vifm-preview) ─────

# Download .debs with apt-get (no install privileges) and merge into ~/.local/opt/vifm-deps.
# On many SSH boxes apt indices exist but apt-get download fails; install_chafa_static fills the gap.
install_vifm_apt_debs() {
    have apt-get || return 0
    have apt-cache || return 0

    local outdir="$HOME/.local/opt/vifm-deps"
    mkdir -p "$outdir"
    local tmpdir
    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    local pkgs=(
        chafa
        libwebpdemux2
        libwebp7
        poppler-utils
        mediainfo
    )
    local p deb
    for p in "${pkgs[@]}"; do
        apt-cache show "$p" &>/dev/null || continue
        (cd "$tmpdir" && apt-get download "$p" 2>/dev/null) || continue
        shopt -s nullglob
        for deb in "$tmpdir"/*.deb; do
            dpkg -x "$deb" "$outdir" || true
            rm -f "$deb"
        done
        shopt -u nullglob
    done

    trap - RETURN INT TERM
}

# Official glibc-linked static tarball (no libwebp). Do not use `have chafa`: a broken apt chafa
# earlier on PATH must not skip installing ~/.local/bin/chafa.
install_chafa_static() {
    [[ -x "$HOME/.local/bin/chafa" ]] && return 0

    local triple archive url tmpdir binroot binpath
    case "$(uname -m)" in
        x86_64)        triple=x86_64-linux-gnu ;;
        armv7l|armv6*) triple=armv7l-linux-gnu ;;
        aarch64|arm64)
            info "chafa: no hpjansson.org static tarball for aarch64; install the distro package or fix apt-get download."
            return 0
            ;;
        *)
            info "chafa: no static build for arch $(uname -m); install chafa from your distro."
            return 0
            ;;
    esac

    archive="chafa-${CHAFA_VERSION}-1-${triple}.tar.gz"
    url="https://hpjansson.org/chafa/releases/static/${archive}"

    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    fetch_soft "$url" "$tmpdir/$archive" || {
        info "chafa: could not fetch ${url}. Install chafa from your package manager."
        trap - RETURN INT TERM
        return 0
    }

    tar -xzf "$tmpdir/$archive" -C "$tmpdir" || {
        trap - RETURN INT TERM
        return 0
    }

    binroot="$tmpdir/chafa-${CHAFA_VERSION}-1-${triple}"
    binpath="$binroot/chafa"
    [[ -x "$binpath" ]] || {
        trap - RETURN INT TERM
        return 0
    }

    mkdir -p "$HOME/.local/bin"
    cp -f "$binpath" "$HOME/.local/bin/chafa"
    chmod +x "$HOME/.local/bin/chafa"
    info "chafa → ~/.local/bin/chafa (static ${CHAFA_VERSION})"

    trap - RETURN INT TERM
}

install_bat_release() {
    have batcat && return 0
    have bat && return 0

    local triple archive url tmpdir extract_dir
    triple=$(github_musl_triple)
    archive="bat-v${BAT_VERSION}-${triple}.tar.gz"
    url="https://github.com/sharkdp/bat/releases/download/v${BAT_VERSION}/${archive}"

    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' RETURN INT TERM

    fetch_soft "$url" "$tmpdir/$archive" || {
        trap - RETURN INT TERM
        return 0
    }

    tar -xzf "$tmpdir/$archive" -C "$tmpdir" || {
        trap - RETURN INT TERM
        return 0
    }

    extract_dir="$tmpdir/bat-v${BAT_VERSION}-${triple}"
    [[ -x "$extract_dir/bat" ]] || {
        trap - RETURN INT TERM
        return 0
    }

    mkdir -p "$HOME/.local/bin"
    cp -f "$extract_dir/bat" "$HOME/.local/bin/bat"
    chmod +x "$HOME/.local/bin/bat"
    ln -sf "$HOME/.local/bin/bat" "$HOME/.local/bin/batcat" 2>/dev/null || true

    trap - RETURN INT TERM
}

vifm_dotfiles_already_configured() {
    local root="$DOTFILES_ROOT"
    [[ -L "${HOME}/.local/bin/vifm-preview" ]] \
        && [[ "$(readlink -f "${HOME}/.local/bin/vifm-preview")" == "$(readlink -f "${root}/vifm/vifm-preview")" ]] \
        && [[ -L "${HOME}/.config/vifm/vifmimgrc" ]] \
        && [[ "$(readlink -f "${HOME}/.config/vifm/vifmimgrc")" == "$(readlink -f "${root}/vifm/vifmimgrc")" ]] \
        && [[ -L "${HOME}/.config/vifm/vifmrc" ]] \
        && [[ "$(readlink -f "${HOME}/.config/vifm/vifmrc")" == "$(readlink -f "${root}/vifm/vifmrc")" ]] \
        && [[ -L "${HOME}/.config/vifm/colors/palenight.vifm" ]] \
        && [[ "$(readlink -f "${HOME}/.config/vifm/colors/palenight.vifm")" == "$(readlink -f "${root}/vifm/colors/palenight.vifm")" ]]
}


install_vifm_preview_deps() {
    install_vifm_apt_debs
    install_chafa_static
}


install_runtime_deps() {
    header "Runtime dependencies"

    if have fzf || have vifm; then
        install_bat_release
    else
        info "Skipping bat (install fzf for ff or vifm for previews)."
    fi

    if have vifm; then
        install_vifm_preview_deps
    else
        info "Skipping vifm preview deps (vifm not installed)."
    fi
}


link_vifm_dotfiles() {
    mkdir -p "$HOME/.local/bin" "$HOME/.config/vifm/colors"

    if [[ ! -r "$DOTFILES_ROOT/vifm/vifm-preview" || ! -r "$DOTFILES_ROOT/vifm/vifmimgrc" || ! -r "$DOTFILES_ROOT/vifm/vifmrc" || ! -r "$DOTFILES_ROOT/vifm/colors/palenight.vifm" ]]; then
        die "missing $DOTFILES_ROOT/vifm/{vifm-preview,vifmimgrc,vifmrc,colors/palenight.vifm}"
    fi

    local failed=0
    link_dotfile "$DOTFILES_ROOT/vifm/vifm-preview" "$HOME/.local/bin/vifm-preview" || ((failed++)) || true
    link_dotfile "$DOTFILES_ROOT/vifm/vifmimgrc" "$HOME/.config/vifm/vifmimgrc" || ((failed++)) || true
    link_dotfile "$DOTFILES_ROOT/vifm/colors/palenight.vifm" "$HOME/.config/vifm/colors/palenight.vifm" || ((failed++)) || true
    link_dotfile "$DOTFILES_ROOT/vifm/vifmrc" "$HOME/.config/vifm/vifmrc" || ((failed++)) || true
    rm -f "$HOME/.local/bin/vifmimg" "$HOME/.local/bin/vifmimg.upstream" "$HOME/.local/bin/vifmrun" 2>/dev/null || true

    if (( failed > 0 )); then
        echo
        info "$failed vifm symlink(s) skipped — regular files or foreign symlinks are in the way."
        info "Run $DOTFILES_ROOT/uninstall.sh then $DOTFILES_ROOT/install.sh for a clean reinstall."
        return 1
    fi
}


# ─── Bashmarks ────────────────────────────────────────────────────────────────
# Provides s, g, p, d, l commands for saving and jumping to directories.
# https://github.com/huyng/bashmarks

install_bashmarks() {
    header "Bashmarks"

    if [[ -f ~/.local/bin/bashmarks.sh ]]; then
        info "Bashmarks already installed (~/.local/bin/bashmarks.sh)."
        return
    fi

    ask "Install Bashmarks (s/g/p/d/l directory bookmarks)?" \
        || { info "Skipping Bashmarks."; return 0; }

    local tmpdir=""
    trap '[[ -n "$tmpdir" ]] && rm -rf "$tmpdir"' RETURN INT TERM
    tmpdir=$(mktemp -d)

    git clone https://github.com/huyng/bashmarks.git "$tmpdir"
    make -C "$tmpdir" install
    info "Bashmarks installed to ~/.local/bin/bashmarks.sh"

    trap - RETURN INT TERM
}


# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
    bootstrap_dotfiles_checkout

    echo
    echo "════════════════════════════════════"
    echo "  Dotfiles Installer"
    echo "════════════════════════════════════"

    check_prerequisites
    install_vim_plug
    install_fzf
    install_fd
    install_bashmarks
    install_vifm
    install_runtime_deps
    refresh_dotfiles_env
    install_dotfiles

    echo
    echo "════════════════════════════════════"
    echo "  Done.  source ~/.bashrc"
    echo "════════════════════════════════════"
    echo
}

main
